apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.app.name }}
spec:
  type: {{ .Values.service.app.type }}
  selector:
    app: {{ .Values.deployment.app.name }}
  ports:
    - protocol: {{ .Values.service.app.protocol }}
      name: {{ .Values.service.app.name }}
      port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.port }}